name: CI/CD
on:
  pull_request:
    branches:
      - production

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js from package.json
        run: |
          NODE_VERSION=$(node -pe "require('./package.json').engines.node")
          echo "Using Node.js version $NODE_VERSION"
          setup-node/setup-node@v3:
            node-version: $NODE_VERSION

      - name: Install Dependencies
        run: npm install

      - name: Testing the branch
        run: npm test

      - name: Building the App
        run: npm run build

      - name: Deploy my code to my server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
            server: link to my ftp
            username: sftpuser
            password: ${{ secrets.sftpuserpwd }}
            local-dir: ./dist
            server-dir: ./var/www/html/react/






            

            





